services:
    prokrustir.dicedev.listener:
        class: prokrustir\dice\event\main_listener
        arguments:
            - '@dbal.conn'
            - '@language'
        tags:
            - { name: event.listener }
